spring:
  h2:
    console:
      enabled: true
      path: /h2 # admin => http://localhost:8080/h2

  jpa:
    database: h2
    show-sql: true

  datasource:
    url: jdbc:h2:file:~/claimants;DB_CLOSE_ON_EXIT=FALSE
    username: claimants
    password: cl4im4nts
    driver-class-name: org.h2.Driver
  jackson:
    serialization:
      write_dates_as_timestamps: false

flyway:
  baseline-on-migrate: true
  schemas: [ "public" ]

dvla-service:
  host: "http://localhost"
  port: 9000
  uri: "/dvla-verify"







